### PR TITLE
correctly decode vs code uris on windows #528

### PR DESCRIPTION
**Pull request by cdietrich**
correctly decode vs code uris on windows #528

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by kittaakos** [comment]
What do you think? Should this pass too?
```java
  @Test
  public void test_toUri_14() {
    Assert.assertEquals(
      URI.createURI("file:///c:/Users/dietrich/\u0424\u0443%20\u0411\u0430\u0440"), 
      this._uriExtensions.toUri("file:///c%3A/Users/dietrich/\u0424\u0443%20\u0411\u0430\u0440"));
  }
```
I would expect yes, but fails with:
```
expected:<file:///c:/Users/dietrich/Фу%20Бар> but was:<file:///c:/Users/dietrich/Фу Бар>
```

Please note, I just added this new test case from a terminal. I might have made typos or misunderstood something.

**Comment by cdietrich** [comment]
this expectation differs from

{code}
	@Test
	def void test_toUri_10() {
		assertEquals(
			createURI('something://dir/\u0424\u0443 \u0411\u0430\u0440'),
			'something://dir/\u0424\u0443 \u0411\u0430\u0440'.toUri
		);
	}
{code}

**Comment by kittaakos** [comment]
Yes, my example is using Windows path, `test_toUri_10` uses UNIX path. As I said, I might have overlooked something.

**Comment by cdietrich** [comment]
i dont know we have tests like: what does vs code pass for spaces?

**Comment by cdietrich** [comment]
`file:///c%3A/Users/dietrich/git/MyDSL_Imports/mydsl/workspace/src/das%20ist%20ein%20test.mydsl`

**Comment by cdietrich** [comment]
next question would be: which encodings do you guys use on windows?
UTF-8 ASCII? Cp1252?

**Comment by kittaakos** [comment]
I always set encoding to UTF-8 if I work on Windows.

**Comment by cdietrich** [comment]
hmmm i dont see any problems with the cyrillic uris in vscode.
=> can somebody test this

**Comment by cdietrich** [comment]
unfortunately our tests run with ISO-8851-1

**Comment by cdietrich** [comment]
=> i am rather clueless

**Comment by cdietrich** [comment]
@svenefftinge @kittaakos  i gave it another try, assuming that the uri we get is always encoded (should be if is rfc)

**Comment by cdietrich** [comment]
no i think file system scanner should use the uri extensions as well

**Comment by cdietrich** [comment]
updated the code. @RealTYPICAL can you please test once more

**Comment by cdietrich** [comment]
@svenefftinge would still like to get your review

**Comment by cdietrich** [comment]
@svenefftinge  are you still alive?

**Pull request merged**
