### PR TITLE
[LanguageServer] Fix HoverService

### PR DESCRIPTION
**Pull request by cdietrich**
Fixes the Hover Service inside the Language Server Impl to support Hovers for Cross References that are not self contained as well.

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by svenefftinge** [comment]
It doesn't seem to work cross resource. Could you add a test to verify?

Am Dienstag, 26. Juli 2016 schrieb Christian Dietrich :

**Comment by cdietrich** [comment]
@svenefftinge it works cross resource. make sure you dont hover over the second half of the last char. (see other issue). ill write a test for that as well. have to find out how this works in junit first

**Comment by cdietrich** [comment]
@svenefftinge i added a test

**Comment by svenefftinge** [comment]
👍 looks good to me

**Pull request merged**
