### PR TITLE
[eclipse/xtext-core#1183]: Fix tests on windows machines.

### PR DESCRIPTION
**Pull request by ArneDeutsch**
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

### CODE REVIEW

**Comment by kittaakos** [comment]
I am checking it...

**Comment by kittaakos** [comment]
I still have three test failures on Windows:

```
> Task :org.eclipse.xtext.ide.tests:test

org.eclipse.xtext.ide.tests.server.CompletionTest > testCompletion_AdditionalEdits_01 FAILED
    org.junit.ComparisonFailure at CompletionTest.java:243

org.eclipse.xtext.ide.tests.server.DocumentTest > testGetLineContent FAILED
    org.junit.ComparisonFailure at DocumentTest.java:219

org.eclipse.xtext.ide.tests.server.SemanticHighlightingTest > testDidOpen_multiLine FAILED
    org.junit.ComparisonFailure at SemanticHighlightingTest.java:318

378 tests completed, 3 failed, 1 skipped
```

I used 930ac50ef.

**Comment by cdietrich** [comment]
yes this fixes only one test.

**Comment by ArneDeutsch** [comment]
I've just run all three test classes from my banch on my windows machine. All succeed. I will run them on master again.

**Comment by ArneDeutsch** [comment]
I can confirm that the tests fail in the branch `ade-backport-windows-test-fixes`. As they succeed all on `ade-newbuild` I will investigate the differences.

**Comment by kittaakos** [comment]
I used pure `CMD.exe` once more, no Cygwin Git Bash tricks this time; it's still failing for me.

```

C:\>git clone --single-branch -b ade-backport-windows-test-fixes https://github.com/eclipse/xtext-core.git
Cloning into 'xtext-core'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 122764 (delta 1), reused 56 (delta 0), pack-reused 122706R
Receiving objects: 100% (122764/122764), 24.81 MiB | 2.48 MiB/s, done.

Resolving deltas: 100% (68253/68253), done.
Checking out files: 100% (7644/7644), done.

C:\>cd xtext-core

C:\xtext-core>git rev-parse --short HEAD
930ac50ef

C:\xtext-core>gradlew clean build

> Task :org.eclipse.xtext:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :org.eclipse.xtext:javadoc
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\formatting2\regionaccess\ITextRegionDiffBuilder.java:36: warning - Tag @link: reference not found: IHiddenRegionPartMerger
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\formatting2\AbstractFormatter2.java:170: warning - Tag @see: reference not found: org.eclipse.xtext.formatting2 The package {@code org.eclipse.xtext.formatting2} for an introduction to the topic
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\formatting2\IFormatter2.java:32: warning - Tag @see: reference not found: org.eclipse.xtext.formatting2 The package org.eclipse.xtext.formatting2 for an introduction to formatting
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\parser\EclipseProjectPropertiesEncodingProvider.java:31: warning - Tag @link: reference not found: org.eclipse.core.internal.preferences.EclipsePreferences
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\generator\OutputConfiguration.java:93: warning - @propertyDescription is an unknown tag.
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\generator\OutputConfiguration.java:93: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\generator\OutputConfiguration.java:93: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\generator\OutputConfiguration.java:93: warning - @propertyDescription is an unknown tag.
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\generator\OutputConfiguration.java:93: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\generator\OutputConfiguration.java:93: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\generator\OutputConfiguration.java:93: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
C:\xtext-core\org.eclipse.xtext\src\org\eclipse\xtext\generator\OutputConfiguration.java:93: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
12 warnings

> Task :org.eclipse.xtext.ide:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :org.eclipse.xtext.testing:compileJava
Note: C:\xtext-core\org.eclipse.xtext.testing\xtend-gen\org\eclipse\xtext\testing\AbstractLanguageServerTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :org.eclipse.xtext.ide.tests:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :org.eclipse.xtext.ide.tests:test

org.eclipse.xtext.ide.tests.server.CompletionTest > testCompletion_AdditionalEdits_01 FAILED
    org.junit.ComparisonFailure at CompletionTest.java:243

org.eclipse.xtext.ide.tests.server.DocumentTest > testGetLineContent FAILED
    org.junit.ComparisonFailure at DocumentTest.java:219

org.eclipse.xtext.ide.tests.server.SemanticHighlightingTest > testDidOpen_multiLine FAILED
    org.junit.ComparisonFailure at SemanticHighlightingTest.java:319

378 tests completed, 3 failed, 1 skipped

> Task :org.eclipse.xtext.ide.tests:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':org.eclipse.xtext.ide.tests:test'.
> There were failing tests. See the report at: file:///C:/xtext-core/org.eclipse.xtext.ide.tests/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 29s
61 actionable tasks: 48 executed, 13 up-to-date

C:\xtext-core>
```

**Comment by ArneDeutsch** [comment]
Not ready.

**Pull request closed without merging**
