### PR TITLE
Fixed #177: typo in AbstractFormatter2.java

### LINKED ISSUE #177: [Formatter 2] Typo in AbstractFormatter2
There is a typo in the `initalize` method, it should be `initialize`.

### PR DESCRIPTION
**Pull request by tivervac**

### CODE REVIEW

**Comment by spoenemann** [comment]
Thanks for the PR! There is also a `@see` link to that method in a comment in line 157.

Contributing to Eclipse projects requires to [set up a CLA](https://www.eclipse.org/legal/CLA.php). Would that be feasible for you?

**Comment by tivervac** [comment]
My CLA should now have been setup, I also committed the requested changes.

**Comment by spoenemann** [comment]
> My CLA should now have been setup, I also committed the requested changes.

Thanks! You also need to sign-off the commits in order to get the ip-validation check green. Something like this should do:
```
git reset origin/master
git commit -s -m "Fixed typo in AbstractFormatter2"
git push -f origin patch-1
```

**Comment by tivervac** [comment]
@spoenemann The branch is now up to date but having executed your commands, whilst forgetting to stage the files before committing, closed the PR.

**Comment by spoenemann** [comment]
Ah yes sorry, of course before creating the commit you have to stage the changes.

**Comment by tivervac** [comment]
Am I still missing out on something or is this ready to be merged in?

**Comment by kittaakos** [comment]
@spoenemann could you please look into this PR again and take care of it. The required changes were performed. Thank you!

**Pull request merged**
