### PR TITLE
added support for Java 9 # 500

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by meysholdt** [comment]
also handle this in `org.eclipse.xtext.xbase.testing.InMemoryJavaCompiler.toClassFmt(JavaVersion)`

**Comment by meysholdt** [comment]
and `org.eclipse.xtext.xbase.ui.builder.XbaseBuilderPreferenceAccess.fromCompilerSourceLevel(String)`

**Comment by meysholdt** [comment]
and `org.eclipse.xtend.ide.tests.WorkbenchTestHelper.getBree(JavaVersion)`

**Comment by meysholdt** [comment]
there is actually more than it makes sense to list here. Calling *find references* on `org.eclipse.xtext.util.JavaVersion` reveals the locations where the new enum literal should be taken into account.

**Pull request merged**
