### PR TITLE
Fixed #238:PolymorphicDispatcher#compare violates contr. of Comparators

### LINKED ISSUE #238: PolymorphicDispatcher#compare violates the contract for Java Comparators
Sometimes, we get the following exception when our Xsemantics-generated type system is initialized:

```
1) Error injecting constructor, java.lang.IllegalArgumentException: Comparison method violates its general contract!
  at eu.numberfour.n4js.typesystem.CustomInternalTypeSystem.<init>(Unknown Source)
  at eu.numberfour.n4js.typesystem.CustomInternalTypeSystem.class(Unknown Source)
  while locating eu.numberfour.n4js.typesystem.CustomInternalTypeSystem
  while locating eu.numberfour.n4js.xsemantics.InternalTypeSystem
    for field at eu.numberfour.n4js.typesystem.N4JSTypeSystem.ts_internal(Unknown Source)
  at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:57)
  while locating eu.numberfour.n4js.typesystem.N4JSTypeSystem
    for field at eu.numberfour.n4js.validation.AbstractN4JSDeclarativeValidator.ts(Unknown Source)
  at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:57)
  while locating eu.numberfour.n4js.validation.validators.N4JSProjectSetupValidator
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at org.eclipse.xtext.util.PolymorphicDispatcher.getDeclaredMethodsOrderedBySpecificParameterType(PolymorphicDispatcher.java:353)
	at org.eclipse.xtext.util.PolymorphicDispatcher.<init>(PolymorphicDispatcher.java:167)
	at org.eclipse.xtext.util.PolymorphicDispatcher.<init>(PolymorphicDispatcher.java:160)
	at it.xsemantics.runtime.XsemanticsRuntimeSystem$2.<init>(XsemanticsRuntimeSystem.java:86)
	at it.xsemantics.runtime.XsemanticsRuntimeSystem.buildPolymorphicDispatcher1(XsemanticsRuntimeSystem.java:86)
	at eu.numberfour.n4js.xsemantics.InternalTypeSystem.init(InternalTypeSystem.java:535)
	at eu.numberfour.n4js.xsemantics.InternalTypeSystem.<init>(InternalTypeSystem.java:531)
	at eu.numberfour.n4js.typesystem.CustomInternalTypeSystem.<init>(CustomInternalTypeSystem.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:85)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at eu.numberfour.n4js.N4JSInjectorProvider$1.createInjector(N4JSInjectorProvider.java:89)
	at eu.numberfour.n4js.N4JSStandaloneSetup.createInjectorAndDoEMFRegistration(N4JSStandaloneSetup.java:80)
	at eu.numberfour.n4js.N4JSInjectorProvider.internalCreateInjector(N4JSInjectorProvider.java:91)
	at eu.numberfour.n4js.N4JSInjectorProvider.getInjector(N4JSInjectorProvider.java:76)
	at eu.numberfour.n4js.N4JSInjectorProvider.setupRegistry(N4JSInjectorProvider.java:101)
	at org.eclipse.xtext.junit4.XtextRunner.methodBlock(XtextRunner.java:43)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:113)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:85)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:134)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Upon further investigation, it turns out that Xtext's `PolymorphicDispatcher`, upon initialization, tries to sort all dispatch methods using a compare method that violates the general contract for Java Comparators. That contract specifies that a compare method should define a total order, i.e., it should be antisymmetric, transitive, and total.

However, there are pairs of methods `(a,b)` where the last requirement is violated. Such methods are incomparable to each other, that is, neither is `a <= b` nor `a <= b`. The compare method returns `0` for such cases, thereby indicating that `a == b`, which is obviously wrong. See the following example:

```
public class PolymorphicDispatcherTest extends PolymorphicDispatcher<Object> {

	public PolymorphicDispatcherTest() {
		super(Collections.singletonList(new Object()), method -> false);
	}

	private Method findMethod(Class<?> current, String name, Class<?>... parameterTypes) {
		if (current == Object.class)
			throw new IllegalArgumentException("Cannot find method");
		try {
			return current.getDeclaredMethod(name, parameterTypes);
		} catch (java.lang.NoSuchMethodException | SecurityException e) {
			return findMethod(current.getSuperclass(), name, parameterTypes);
		}
	}

        private static class S {}

	private static class A extends C {
	}

	private static class B extends S {
	}

	private static class C extends S {
	}

	public void test(A a) {
	}

	public void test(B b) {
	}

	public void test(C c) {
	}

	public void showTransitivityViolation() {
		MethodDesc m1 = createMethodDesc(this, findMethod(getClass(), "test", A.class));
		MethodDesc m2 = createMethodDesc(this, findMethod(getClass(), "test", B.class));
		MethodDesc m3 = createMethodDesc(this, findMethod(getClass(), "test", C.class));

		int m1m2 = PolymorphicDispatcherTest.this.compare(m1, m2); // 0
		int m2m3 = PolymorphicDispatcherTest.this.compare(m2, m3); // 0
		int m1m3 = PolymorphicDispatcherTest.this.compare(m1, m3); // 1

		if (m1m2 <= 0 && m2m3 <= 0 && !(m1m3 <= 0))
			throw new IllegalStateException("Transitivity violation");
	}

	public static void main(String[] args) {
		PolymorphicDispatcherTest test = new PolymorphicDispatcherTest();
		test.showTransitivityViolation();
	}
}
```

In this example, the method returns `0` when comparing method pairs `m1,m2` and `m2,m3`, even though in both cases, the methods are not identical! Comparing `m1` and `m3` then yields `1`, which violates transitivity.

We think the problem is due to the fact that the subtype relation, on which the compare method is based, only defines a partial order. The compare method attempts to extend this to a total order in an incorrect way.

This exception is thrown only sometimes, and it has popped up only recently (to our knowledge). We think that this is due to the fact that the initial order of the methods to be sorted depends on the initial order of the methods returned by `Class#getDeclaredMethods`, which is undefined by Java. Furthermore, Java uses different sorting algorithms depending on the number of elements to be sorted. In our particular cases, we are trying to sort 59 methods.

### PR DESCRIPTION
**Pull request by meysholdt**
This change implements the same strategy for PolymorphicDispatch which
is already in place for Xtend's 'dispatch' methods:

see org.eclipse.xtend.core.jvmmodel.DispatchHelper.compare(...)
see https://github.com/eclipse/xtext-core/issues/238

Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

### CODE REVIEW

**Comment by meysholdt** [comment]
👎 for including this change the 2.11er release, because it potentially changes semantics when combining dispatch methods from multiple classes, because the following implication does *not* hold true:

`∀ class1, class2: (!class1.isAssignableFrom(class2) || !class2.isAssignableFrom(class1)) => (getMaxDistanceToObject(class1) == getMaxDistanceToObject(class2))`

**Comment by LorenzoBettini** [comment]
@meysholdt I did something slightly difference in this experiment: 

https://github.com/LorenzoBettini/polymorphic.dispatcher.experiments/blob/master/polymorphic.dispatcher.experiments/src/polymorphic/dispatcher/experiments/PolymorphicDispatcherTotalOrder.java

First

https://github.com/LorenzoBettini/polymorphic.dispatcher.experiments/blob/master/polymorphic.dispatcher.experiments/src/polymorphic/dispatcher/experiments/PolymorphicDispatcherTotalOrder.java#L210 imposes a total order in case of a single target (as suggested by @JensN4 ), used when sorting the list

However, the comparison for methods is in a separate method that also returns a status saying that two methods are unrelated, and this is used when looking for candidates to be invoked: https://github.com/LorenzoBettini/polymorphic.dispatcher.experiments/blob/master/polymorphic.dispatcher.experiments/src/polymorphic/dispatcher/experiments/PolymorphicDispatcherTotalOrder.java#L276

Does this make sense to you?

**Comment by meysholdt** [comment]
I see. That is in fact less invasive than what I did.

**Comment by LorenzoBettini** [comment]
OK, then I'll create a different PR if you think that's worthwhile.

By the way, there's also this:

java.util.Arrays.sort(Object[])

```Java
    /**
     * Old merge sort implementation can be selected (for
     * compatibility with broken comparators) using a system property.
     * Cannot be a static boolean in the enclosing class due to
     * circular dependencies. To be removed in a future release.
     */
    static final class LegacyMergeSort {
        private static final boolean userRequested =
            java.security.AccessController.doPrivileged(
                new sun.security.action.GetBooleanAction(
                    "java.util.Arrays.useLegacyMergeSort")).booleanValue();
    }
```

but it says that it'll be removed in the future...

**Comment by cdietrich** [comment]
so bad idea to use -Djava.util.Arrays.useLegacyMergeSort=true

**Comment by meysholdt** [comment]
thx, but you don't need to, I've already started

**Comment by LorenzoBettini** [comment]
@cdietrich indeed, I was just mentioning that :)
@meysholdt have you started with my proposal?

**Comment by meysholdt** [comment]
@LorenzoBettini yes, see #249

**Comment by LorenzoBettini** [comment]
Thanks! Yours is even better :)

**Comment by meysholdt** [comment]
fixed in https://github.com/eclipse/xtext-core/commit/923422737ed632756d4670dcfb7b079ecc5b5252

**Pull request closed without merging**
