### PR TITLE
[releng] Update Gradle Wrapper to 5.6.4

### PR DESCRIPTION
**Pull request by genie-xtext**
This change was brought to you by your friendly Xtext Genie.

### CODE REVIEW

**Comment by cdietrich** [comment]
miss a change to the resources. also dont know if this can handle changes to the jar or gradlew.bat or gradlew too

**Comment by kthoms** [comment]
These changes are the result of the command `./gradlew wrapper --gradle-version 5.6.4`. If the wrapper jar or the scripts change this should occur here, too.

With `resources` you mean `org.eclipse.xtext.xtext.wizard/resources/gradlew`? I noticed that gradle files should be copied to there, but there seems to be a bug in the script.

**Comment by cdietrich** [comment]
yes
```
./org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties                                                                           
./org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties                                                                     
./org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/wrapper/gradle-wrapper.properties                                                                                         
./org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/wrapper/gradle-wrapper.properties                                                                                     
./org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties                                                                                                                                                                 
./gradle/wrapper/gradle-wrapper.properties```

**Comment by cdietrich** [comment]
please also note:

you have to execute `gradlew wrapper` twice to get updated scripts and jar

**Pull request closed without merging**
