### PR TITLE
[#108] Ecore2Xtext use new formatter fragment

### PR DESCRIPTION
**Pull request by kthoms**
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
If I understand correctly, the Formatter2Fragment2 does something like

	protected def doGenerateStubFile() {
		if(!isGenerateStub)
			return;
			
		if(isGenerateXtendStub) {...
		} else {
			LOG.error(this.class.name + " has been configured to generate a Java stub, but that's not yet supported. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=481563")	
		}
	}

Thus, if you specify generateStub=true but no generateXtendStub you'll get an error during the mwe2 run, is that correct?

**Comment by kthoms** [comment]
isGenerateXtendStub returns true without setting the value explicitly. Have a look into AbstractStubGeneratingFragment#isGenerateXtendStub. Since codeConfig has preferXtendStubs=true by default and the property is not explicitly set, the value isGenerateXtendStub defaults to preferXtendStubs.

**Comment by LorenzoBettini** [comment]
OK! I couldn't try that right now and I remember that in the past I had that problem, but something must have changed in the meantime :)

**Comment by LorenzoBettini** [comment]
@kthoms I think this should now be rebased/merged with master due to the other merged PRs.

**Comment by kthoms** [comment]
@LorenzoBettini Rebased. Please review again.

**Pull request merged**
