### PR TITLE
[406914] Explicitly map identifiers for tab, cr and lf

### PR DESCRIPTION
**Pull request by kthoms**
The underlying ICU transliterator maps the special characters to
'Control'<code>, so these characters have to be mapped without using
ICU. Further to keep camel case of the mapped text the text is mapped
directly in toJavaIdentifierSegment.

Signed-off-by: Karsten Thoms karsten.thoms@itemis.de

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=406914

**Comment by spoenemann** [comment]
What about tests for that issue? The original issue mentioned

> This bug occurred in /org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/antlr/Bug301935TestLanguage.xtext

**Comment by kthoms** [comment]
Updated.

**Comment by JanKoehnlein** [comment]
How about \f, \b or unicode chars with \u?
Are ambiguities handled, e.g. for a rule

Foo:
   '\n' | 'newline';

**Comment by kthoms** [comment]
Ambiguities are handled as before, they get a count suffix. See new test language Bug406914TestLanguage.
Handled additionally \b, \f, \\.
For unicode the behavior has not changed and is beyond scope of the referred bug.

**Comment by kthoms** [comment]
Shall I extend the new example by a keyword with unicode?

**Comment by kthoms** [comment]
Is there more action required now? Please review.

**Comment by spoenemann** [comment]
Looks good now.

**Pull request merged**
