### PR TITLE
Windows tests fix (linesep)

### PR DESCRIPTION
**Pull request by DelRed2**
Some tests are falling due to windows line separators.
Fix it.

### CODE REVIEW

**Comment by spoenemann** [comment]
Thank you! Please [submit an ECA](https://www.eclipse.org/legal/ECA.php) and sign off your commit (`git commit -s --amend`).

**Comment by DelRed2** [comment]
Also, there are failing tests on windows build:
    TracingSugarTest > testCodeGeneration
    CliWizardIntegrationTest > testProjectCreation
due to windows line separators, but I don't know how to fix it.

**Comment by spoenemann** [comment]
> Also, there are failing tests on windows build:
> TracingSugarTest > testCodeGeneration
> CliWizardIntegrationTest > testProjectCreation
> due to windows line separators, but I don't know how to fix it.

Could you create an issue for that?

**Comment by DelRed2** [comment]
https://github.com/eclipse/xtext-core/issues/343

**Pull request merged**
