### PR TITLE
Add gitpod config

### PR DESCRIPTION
**Pull request by tivervac**
@cdietrich This might be useful, I just did an xtend -> java review on gitpod and that was a lot better than just using the github web view

### CODE REVIEW

**Comment by cdietrich** [comment]
i am not sure about the licensing/pricing conditions for that. can you help out @svenefftinge

**Comment by tivervac** [comment]
For open source project it appears to be free for 50 hours/month but I guess that's for the user, not the organisation?

**Comment by miklossy** [comment]
There have been already such initiatives by @JanKoehnlein in the past, see [PR](https://github.com/eclipse/xtext-core/pull/1285)

**Comment by szarnekow** [comment]
@tivervac do you plan to improve this further?

**Comment by tivervac** [comment]
Having read the history, no. I'll close it

**Pull request closed without merging**
