### PR TITLE
[515846] Don't call getTraceToTarget when src project config unavailable

### PR DESCRIPTION
**Pull request by kthoms**
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=515846

**Comment by cdietrich** [comment]
@kthoms is this pr obsolte by your other changes?

**Comment by kthoms** [comment]
Hmm, getProjectConfig might return null, and getTraceToTarget handles the null argument. Seems that this is not really neccessary, maybe just more explicit. What do you think? Change or drop?

**Comment by cdietrich** [comment]
you introduced another pr for the null check. please check the history

**Comment by cdietrich** [comment]
i consider it as obsolete and thus will close

**Pull request closed without merging**
