### PR TITLE
Adapt Lifecycle Mappings to changes in tycho

### PR DESCRIPTION
**Pull request by cdietrich**
Adapt Lifecycle Mappings to changes in tycho
See https://github.com/itemis/xtext-reference-projects/issues/194

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by cdietrich** [comment]
please review after the fact

**Comment by LorenzoBettini** [comment]
I had to change these in other projects as well, and they work fine!

**Comment by cdietrich** [comment]
thx for the feedback @LorenzoBettini

**Pull request merged**
