### PR TITLE
[380449] Enhancements to Task Finder

### PR DESCRIPTION
**Pull request by cdietrich**
[380449] Enhancements to Task Finder

- Introduced a hook to allow stripping of the node text before calling the task parser
- Stripped trailing comment in tasks

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=380449

**Comment by svenefftinge** [comment]
It would be better to reuse something like 'org.eclipse.xtext.documentation.impl.AbstractMultiLineCommentProvider.getTextFromMultilineComment(String)' to identify any terminals to strip off.

**Comment by cdietrich** [comment]
well that one is non api so i cannot use it

**Comment by svenefftinge** [comment]
I think adding 
```
        public String getDocumetation(String rawToken) {
		return getTextFromMultilineComment(rawToken);
	}
```
would be good.

**Comment by cdietrich** [comment]
hmmmm, and directly inject the  provider? at other places IEObjectDocumentationProvider(Extension) is used

**Comment by svenefftinge** [comment]
No that doesn't sound good. 
Let's instead than just reuse `endTag` from `AbstractMultiLineCommentProvider.MultiLineCommentProviderProperties` with the same default as in `AbstractMultiLineCommentProvider`

**Comment by cdietrich** [comment]
wont work, MultiLineCommentProviderProperties is private

**Comment by cdietrich** [comment]
@svenefftinge can you please have a look again?

**Pull request merged**
