### PR TITLE
[410605]  [grammar][terminal] Validate that EOF cannot be inverted

### PR DESCRIPTION
**Pull request by cdietrich**
[410605]  [grammar][terminal] Validate that EOF cannot be inverted
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=410605

**Comment by svenefftinge** [comment]
how about things like 
```
terminal UNCLOSED_COMMENT: '/*' !(EOF | NEW_LINE) (EOF | NEWLINE);
```

**Comment by cdietrich** [comment]
updated

**Pull request merged**
