### PR TITLE
https://github.com/Microsoft/language-server-protocol/blob/master/pro…

### PR DESCRIPTION
**Pull request by RealTYPICAL**
…tocol.md Server should exit with success or fail code when exit has been called.

Exit Notification

A notification to ask the server to exit its process. The server should exit with success code 0 if the shutdown request has been received before; otherwise with error code 1.

Notification:

method: 'exit'
params: void

from https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

Signed-off-by: James Tooley jetter019@msn.com

### CODE REVIEW

**Comment by kthoms** [comment]
Thanks James for the contribution. Please sign an [ECA](https://www.eclipse.org/legal/ECA.php), this is mandatory for contributions.

**Comment by cdietrich** [comment]
and you need to signoff the commits

**Comment by RealTYPICAL** [comment]
I just signed an ECA. How long does that process take? Also updated the commit message to include a sign off. Hope that's what you meant.

**Comment by cdietrich** [comment]
Sign and cla mail must match

**Comment by kthoms** [comment]
At the moment there is a mismatch. [IP-validation](https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=59ca2fc6c380a) mentions email james.tooley (at) kpit.com, commit sign-off is with jetter019 (at) msn.com.
You have to sign off with information you used in the ECA. If this requires to change the commit, please amend the change and overwrite the original one with a force push.
Sorry for the inconvenience.

**Comment by kthoms** [comment]
James, we really appreciate your efforts and would like to support you getting your change in. There is still a mismatch between the email address of your ECA and the sign-off address. Maybe it is easier for you to create another PR. Seems that you messed up your master branch a bit.

Maybe you should overwrite your master with origin's master. Then create a branch for your change, redo the change and make sure to sign off the commit with the ECA email address. Push that branch to your repo and create a new PR.

**Comment by kthoms** [comment]
Replaced by #474

**Pull request closed without merging**
