### PR TITLE
#1223 Generate MWE2 workflow in way to generate java code.

### PR DESCRIPTION
**Pull request by ArneDeutsch**
#1223 Generate MWE2 workflow in way to generate java code.

Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@ArneDeutsch can you please have a look at the test failures?

**Comment by cdietrich** [comment]
ping @ArneDeutsch

**Comment by cdietrich** [comment]
moved to 2.20

**Comment by ArneDeutsch** [comment]
Adapted test expectations.

**Comment by cdietrich** [comment]
@kthoms @ArneDeutsch i propose to merge this (and the documentation change)
now and do the flag in the wizard later

**Comment by szarnekow** [comment]
> @kthoms @ArneDeutsch i propose to merge this (and the documentation change)
> now and do the flag in the wizard later

This sounds like a good move forward to me, too.

**Pull request merged**
