### PR TITLE
Gradle composite

### PR DESCRIPTION
**Pull request by kthoms**
connection.project.dir changed to composite build location in new
umbrella project
value 'containers' added by Buildship

Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@dhuebner did you use oomph to setup. oomph checks out like

```
xtext-lib
...
xtext-umbrella
```

**Comment by kthoms** [comment]
Yes, I used the adjusted setup from https://github.com/eclipse/xtext-eclipse/pull/118, and with import of the composite Gradle projects Buildship did these changes automatically.

**Comment by svenefftinge** [comment]
do we need to checkin the buildship prefs at all?

**Comment by cdietrich** [comment]
yes otherwise buildship wont do the container for dependencies right

**Comment by kthoms** [comment]
Yes, as long as Oomph has no "Import Gradle project" plugin. It can only import existing projects, and Buildship requires to have these settings then.

**Comment by cdietrich** [comment]
or we would have to write a oomph task for buildship import
i dont know how easy complicated that would be

**Comment by kthoms** [comment]
I think we could contribute such a thing for Oomph in mid-term, and then we may get rid of this here.

**Comment by dhuebner** [comment]
@cdietrich That sounds like a plan. Or try to use "Resource creation" or "Text Modify" task

**Comment by cdietrich** [comment]
the question is: will we go with the "old" buildship version until then?

**Comment by cdietrich** [comment]
generating the prefs files seems to work

**Comment by kthoms** [comment]
This works with Oomph in principle. I have to fix the setup a bit. Then we could remove the Buildship preferences and add them to .gitignore.

**Comment by cdietrich** [comment]
@dhuebner is this ok for you?

**Comment by kittaakos** [comment]
I have just tried out the new changes. Currently, I have only xtext-core projects in the workspace, I do not care about anything else. I figured out, I have to clone the umbrella repository as well and I have to manually run the buildship preference generations. Worked fine but it did not generate anything to the xtext-core parent folder. Is that intentional? I would appreciate any feedback. Plus, I think it would be great to write down the required steps to somewhere. Otherwise, it might cause problems for contributors. (I am happy to write some short TODO list if it does not exist yet. If so, please tell me where to put it.)

**Comment by kittaakos** [comment]
I have just noticed there are other projects where the generation was not applied. For instance:
<ul>
<li>org.eclipse.xtext.testlanguages</li>
<li>org.eclipse.xtext.testlanguages.ide</li>
</ul>

That was my output for the xtext-core projects:
<pre>
...
generating buildship prefs for /Users/akos.kitta/git/xtext-core/org.eclipse.xtext
generating buildship prefs for /Users/akos.kitta/git/xtext-core/org.eclipse.xtext.ide
generating buildship prefs for /Users/akos.kitta/git/xtext-core/org.eclipse.xtext.ide.tests
generating buildship prefs for /Users/akos.kitta/git/xtext-core/org.eclipse.xtext.testing
generating buildship prefs for /Users/akos.kitta/git/xtext-core/org.eclipse.xtext.tests
generating buildship prefs for /Users/akos.kitta/git/xtext-core/org.eclipse.xtext.util
generating buildship prefs for /Users/akos.kitta/git/xtext-core/org.eclipse.xtext.xtext.generator
generating buildship prefs for /Users/akos.kitta/git/xtext-core/org.eclipse.xtext.xtext.wizard
...
</pre>

Generation for other core projects was ignored.

**Comment by cdietrich** [comment]
@kittaakos did you use the oomph setup?

**Comment by cdietrich** [comment]
@kthoms @kittaakos can you change if these projects have settings files?
i need some method to detect if a project is one we are interested in is a gradle project and i look if it has a settings file. @oehme is there an easier way to get all gradle projects for a folders?

**Comment by kittaakos** [comment]
@cdietrich No, I did not use oomph in the workspace. I just imported the xtext-core repository content, since that was all I needed for my current task.

> can you change if these projects have settings files?

Sorry, did you mean to check? If no, can you please clarify a bit?

**Comment by cdietrich** [comment]
my log says

```
generating buildship prefs for /data/xtext-dev2/xtext-master/git/xtext-core/org.eclipse.xtext.tests
generating buildship prefs for /data/xtext-dev2/xtext-master/git/xtext-core/org.eclipse.xtext.ide
generating buildship prefs for /data/xtext-dev2/xtext-master/git/xtext-core/org.eclipse.xtext
generating buildship prefs for /data/xtext-dev2/xtext-master/git/xtext-core/org.eclipse.xtext.xtext.generator
generating buildship prefs for /data/xtext-dev2/xtext-master/git/xtext-core/org.eclipse.xtext.util
generating buildship prefs for /data/xtext-dev2/xtext-master/git/xtext-core/org.eclipse.xtext.testlanguages
generating buildship prefs for /data/xtext-dev2/xtext-master/git/xtext-core/org.eclipse.xtext.ide.tests
generating buildship prefs for /data/xtext-dev2/xtext-master/git/xtext-core/org.eclipse.xtext.xtext.wizard
generating buildship prefs for /data/xtext-dev2/xtext-master/git/xtext-core/org.eclipse.xtext.testing
```

=> i dont get where the prefs are missing

and i dont know why you need generate prefs at all. 
using the buildship import wizard should do the same

**Comment by cdietrich** [comment]
org.eclipse.xtext.testlanguages.ide has no .settings folder i dont know why

**Comment by kthoms** [comment]
Contributors have to either use Oomph (recommended by the contribution guide) or import the parent project(s) with Gradle Project Import. In both cases the Buildship preferences should be obsolete.

**Comment by cdietrich** [comment]
can you have a look at https://github.com/eclipse/xtext-umbrella/tree/bettergen

**Comment by kittaakos** [comment]
> and i dont know why you need generate prefs at all.
> using the buildship import wizard should do the same

So I need to re-import them with the Gradle wizard, right? My projects were already in the workspace. The only thing I did is merging the xtext origin/masters to my forks. I will try with the Gradle import again and let you know my results.

**Comment by cdietrich** [comment]
a gradle refresh gradle projects should do the same, but if you dont use umbrella you should not generate

**Comment by kittaakos** [comment]
> a gradle refresh gradle projects should do the same

But it did not. Indeed I tried that but nothing happened because the buildship preference files were missing. Or am I wrong?

Anyway, I have created a fresh workspace with no projects and ran the Gradle import wizard on the xtext-core parent folder. This is what I got, below. Could you please advise who I should proceed? Thanks!

<pre>
org.gradle.tooling.UnsupportedVersionException: The version of Gradle you are using (3.2) does not support the CompositeModelBuilder API. Support for this is available in Gradle 2.14 and all later versions.
	at org.gradle.tooling.model.internal.Exceptions.unsupportedFeature(Exceptions.java:66)
	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.buildModels(AbstractConsumerConnection.java:73)
	at org.gradle.tooling.internal.connection.DefaultCompositeModelBuilder$1.run(DefaultCompositeModelBuilder.java:92)
	at org.gradle.tooling.internal.connection.DefaultCompositeModelBuilder$1.run(DefaultCompositeModelBuilder.java:86)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:79)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.connection.DefaultCompositeModelBuilder.get(DefaultCompositeModelBuilder.java:74)
	at org.gradle.tooling.internal.connection.DefaultCompositeModelBuilder.get(DefaultCompositeModelBuilder.java:40)
	at com.gradleware.tooling.toolingclient.internal.deduplication.DelegatingModelBuilder.get(DelegatingModelBuilder.java:141)
	at com.gradleware.tooling.toolingclient.internal.deduplication.DeduplicatingGradleConnection$DeduplicatingEclipseModelBuilder.get(DeduplicatingGradleConnection.java:93)
	at com.gradleware.tooling.toolingclient.internal.deduplication.DeduplicatingGradleConnection$DeduplicatingEclipseModelBuilder.get(DeduplicatingGradleConnection.java:85)
	at com.gradleware.tooling.toolingclient.internal.DefaultToolingClient.executeAndWait(DefaultToolingClient.java:210)
	at com.gradleware.tooling.toolingclient.internal.DefaultCompositeBuildModelRequest.executeAndWait(DefaultCompositeBuildModelRequest.java:47)
	at com.gradleware.tooling.toolingclient.internal.DefaultCompositeBuildModelRequest.executeAndWait(DefaultCompositeBuildModelRequest.java:31)
	at com.gradleware.tooling.toolingmodel.repository.internal.BaseModelRepository$1.get(BaseModelRepository.java:95)
	at com.gradleware.tooling.toolingmodel.repository.internal.BaseModelRepository.executeAndWait(BaseModelRepository.java:163)
	at com.gradleware.tooling.toolingmodel.repository.internal.BaseModelRepository.access$000(BaseModelRepository.java:41)
	at com.gradleware.tooling.toolingmodel.repository.internal.BaseModelRepository$2.call(BaseModelRepository.java:121)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4724)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4721)
	at com.gradleware.tooling.toolingmodel.repository.internal.BaseModelRepository.getFromCache(BaseModelRepository.java:138)
	at com.gradleware.tooling.toolingmodel.repository.internal.BaseModelRepository.executeRequest(BaseModelRepository.java:117)
	at com.gradleware.tooling.toolingmodel.repository.internal.BaseModelRepository.executeRequest(BaseModelRepository.java:88)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultCompositeModelRepository.executeRequest(DefaultCompositeModelRepository.java:99)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultCompositeModelRepository.fetchEclipseProjects(DefaultCompositeModelRepository.java:63)
	at org.eclipse.buildship.core.workspace.internal.DefaultCompositeModelprovider.fetchEclipseProjects(DefaultCompositeModelprovider.java:39)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeCompositeBuildJob.fetchEclipseProjects(SynchronizeCompositeBuildJob.java:72)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeCompositeBuildJob.runToolingApiJob(SynchronizeCompositeBuildJob.java:65)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:63)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
</pre>

**Comment by kittaakos** [comment]
Another note, each time I run the Gradle import wizard and of course I cannot complete it due to the above-described reasons, I have a stale java process that was spawned by the wizard. And it remains after I close the wizard.

**Comment by cdietrich** [comment]
@oehme do you have an idea?

**Comment by cdietrich** [comment]
@kittaakos did you delete the prefs files before importing?

**Comment by oehme** [comment]
@kittaakos Looks like you are using an old Buildship milestone. Please make sure you are using the latest milestone.

**Comment by kthoms** [comment]
@kittaakos Which Buildship version are you using? I tried to import with 1.x before and had a similar (not identical) problem. With version 2.0.0.v20161108-1534-m from http://download.eclipse.org/buildship/updates/e45/milestones/2.x/ I could import a fresh cloned xtext-core project.

**Comment by oehme** [comment]
Also if you just want the core project, you don't need the umbrella. Just import the core project with the Gradle import wizard. The umbrella is only there for the Oomph setup.

**Comment by kittaakos** [comment]
> The umbrella is only there for the Oomph setup.

I did not use the umbrella for the fresh workspace, just xtect-core.

But I will try out with the latest buildship version. Probably that is the problem. Thanks for the pointers!

**Comment by kittaakos** [comment]
OK, I can confirm that after cloning my xtext-core fork again and starting an Eclipse with a fresh new workspace I managed to import the parent xtext-core folder with the [latest] Gradle tooling feature.
The workspace was built correctly.

Many thanks to all of you for the help!

[latest]: http://download.eclipse.org/buildship/updates/e45/milestones/2.x/

**Pull request merged**
