### PR TITLE
Fix typo in class name DocumentSymbolConfiguration

### PR DESCRIPTION
**Pull request by rubenporras**
Signed-off-by: Rubén Porras Campo <pcr@avaloq.com>

### CODE REVIEW

**Comment by miklossy** [comment]
I am not sure if this change is considered as an API break.
@cdietrich : What do you think?

**Comment by cdietrich** [comment]
i dont care in this area. lsp4j breaks all the time

**Comment by rubenporras** [comment]
I am also not sure how you handle the test API. If you consider it a breaking change, I can submit an updated version that leaves the old class in place with a deprecated annotation.

**Review by miklossy — APPROVED** [review]

**Comment by miklossy** [comment]
Thx @rubenporras !

**Pull request merged**
