### PR TITLE
provided more 'disabled' fragments to ease workflow customization

### PR DESCRIPTION
**Pull request by cdietrich**
provided more 'disabled' fragments to ease workflow customization
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
meanwile stting e.g.,
```
JunitSupport = null

```
is working, thus this is obsolete

**Comment by miklossy** [comment]
@cdietrich: Do you see any places in the Xtext-Exampes where disabling the generation fragments could be defined in a more elegant/readable manner?

**Comment by cdietrich** [comment]
?

**Comment by miklossy** [comment]
I mean if you consider e.g the worklow definition of the Xtext Arithmetics example https://github.com/eclipse/xtext-eclipse/blob/77876803d5427677630ccff80a51fad3706ba246/org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src/org/eclipse/xtext/example/arithmetics/GenerateArithmetics.mwe2#L52

the generator fragment is currently disabled. Do you think defining it using generator = null or generator = Disabled would be better readable/more explanatory?

**Comment by cdietrich** [comment]
generator = null and generateStub=false is not the same
(have a look at the binding and plugin.xml of the ui project)

**Comment by miklossy** [comment]
I see. Do you think that `generator = null` would be a better choice to complete disable the generator fragment in case of the Xtext Arithmetics exmaple?

**Comment by cdietrich** [comment]
you know more about the example than i do. so i dont know

**Comment by miklossy** [comment]
I think using `generator = null` would be a better choice there.
@szarnekow What do you think?

**Comment by szarnekow** [comment]
@miklossy with `generateStub = false` you still get a preference page for the compiler by default. That does not make too much sense. `generator = null` may improve that.

**Comment by miklossy** [comment]
I had the same assumption, but I was not sure about that. Thanks for clarifying that, @szarnekow !
I created the corresponding [PR](https://github.com/eclipse/xtext-eclipse/pull/1386) to clean up the Xtext SimpleArithmetics example.

**Pull request closed without merging**
