### PR TITLE
[eclipse/xtext#2134] remove dependency to obsolte jdt.compiler.(tool|apt)

### PR DESCRIPTION
**Pull request by cdietrich**
[eclipse/xtext#2134] remove dependency to obsolte jdt.compiler.(tool|apt)

### CODE REVIEW

**Comment by cdietrich** [comment]
@LorenzoBettini can i merge this now to have a green build again?

**Comment by LorenzoBettini** [comment]
@cdietrich I still haven't got time to test it personally, but I think we can merge it. The fragments were needed because there were no other ways to force them in the TP (when jdt.core was also present). Now that the fragments are gone, we should be safe without them (as long as they are also removed from the dependencies of the maven plugin `xtext-maven-plugin`).

**Comment by cdietrich** [comment]
@LorenzoBettini the point is that they are not, cause we are still on old platform from a maven perspective
thus i wanted you to have a look

**Comment by LorenzoBettini** [comment]
@cdietrich OK, I see. Then I'll try to do that ASAP. I'm actively working on https://github.com/eclipse/xtext-core/issues/2052 for the moment.

I guess it won't be a problem anyway, because we won't have a mixture of apt and tool from the TP, because from the TP point of view those fragments are not there anymore.

I guess that, from the xtext-maven-plugin point of view:
- if jdt.core is taken from the more recent TP and apt from the old Maven dep, apt will not simply be used
- if jdt.core is taken from the old Maven dep it will also find the old apt, so it should be fine

**Comment by cdietrich** [comment]
gonna merge for now, if more adjustment needed we need a second pr anyway

**Pull request merged**
