### PR TITLE
[LS] Added basic signature help support for the test language.

### PR DESCRIPTION
**Pull request by kittaakos**
Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

**Comment by meysholdt** [comment]
copied branch to 
https://github.com/eclipse/xtext-core/tree/me_ak_signaturehelp_testlang_signedoff
to have a build here:
http://services.typefox.io/open-source/jenkins/job/xtext-core/job/me_ak_signaturehelp_testlang_signedoff/

**Comment by kittaakos** [comment]
Hey @meysholdt, do you have a clue why my most recent commit violates the IP constraint? Thanks! Should I create a new PR (again) ?

**Comment by cdietrich** [comment]
@kittaakos  https://projects.eclipse.org/user/cla/validate says no valid cla for your email

**Comment by svenefftinge** [comment]
Awesome, thank you! (the CLA is valid now)

**Pull request merged**
