### PR TITLE
[eclipse/xtext#1182] fixed tests with java 11 agains java 8 target

### PR DESCRIPTION
**Pull request by cdietrich**
[eclipse/xtext#1182] fixed tests with java 11 agains java 8 target
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
fixes
```
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.compare [22]
  Unresolved requirement: Require-Bundle: org.eclipse.ui.ide; bundle-version="[3.3.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.ui.ide; bundle-version="3.14.200.v20181003-0856"; singleton:="true"
       org.eclipse.ui.ide [26]
         Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.106.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.110.0.v20180828-1350"; singleton:="true"
              org.eclipse.ui [23]
                Unresolved requirement: Require-Bundle: org.eclipse.ui.workbench; bundle-version="[3.112.0,4.0.0)"; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.ui.workbench; bundle-version="3.112.100.v20181005-0915"; singleton:="true"
                     org.eclipse.ui.workbench [106]
                       Unresolved requirement: Import-Package: javax.annotation```

**Comment by LorenzoBettini** [comment]
On a side note, the comments in the POMs are misleading, from what I understand.
I added those comments when I added those sections in the ui.tests (for which, from what I understand, are still required). In headless tests the feature is required for the missing javax.annotation, isn't it?
@cdietrich @kthoms

**Comment by LorenzoBettini** [comment]
I understand it is a temporary workaround, but since that's in the generated POMs (which will not be regenerated by clients when a new version of Xtext is released), the misleading comments will give no clues to the clients and they probably won't remove the workaround.

**Comment by cdietrich** [comment]
feel free to provide a pr for master replacing the comment with something better

**Comment by LorenzoBettini** [comment]
OK, but do you happen to know whether Tycho 1.4.0 (which fixes this problem) is released before Xtext 2.18.0?

**Comment by cdietrich** [comment]
i dont know. i would expect to see the new tycho soon after as platform has published maven artifacts for 2019-03 but i dont see a release planned

**Comment by cdietrich** [comment]
will ask

**Comment by LorenzoBettini** [comment]
OK, if you have news about that please let me know and in case I can provide a PR

**Comment by cdietrich** [comment]
from @mickaelistria on tycho-user
>The best we can say is "soon".
>I'll try to stage it later today (no guarantee) and share the staging URL
for testing. Then, if there is no objection, we'll try release it next week.
>I'll be taking care of this process for the 1st time ever as Jan is
currently not available to do it. So expect some glitches and be forgiving
>Some more news either within a few hours in the best case, or on Monday in
the hopefully worst case.

**Comment by LorenzoBettini** [comment]
OK, so let's just wait for it to be released, there's no need to change the current code base :)

**Comment by mickaelistria** [comment]
Unless you're planning a release of XText very soon, you can also configure the build to use Tycho 1.4.0-SNAPSHOT.

**Comment by LorenzoBettini** [comment]
@cdietrich would it make sense to fix the comments for 2.17.1?
when is it scheduled?

**Comment by cdietrich** [comment]
could you provide a pr?
will discuss with the team?

**Comment by cdietrich** [comment]
we plan to release it today or tomorrow

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-core/tree/2.17_maintenance

**Comment by LorenzoBettini** [comment]
mh... I'm unable to do that today I'm afraid... :(
maybe tomorrow, but only in the afternoon... I guess that's too late, isn't it?

**Comment by cdietrich** [comment]
then i will do.

**Comment by LorenzoBettini** [comment]
Thank you!

**Pull request merged**
