### PR TITLE
added missing types to CodeGenUtil2.getJavaDefaultTypes() #509

### PR DESCRIPTION
**Pull request by cdietrich**
added missing types to CodeGenUtil2.getJavaDefaultTypes() #509

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by cdietrich** [comment]
@svenefftinge i am not sure if this should already go into 2.13

**Comment by cdietrich** [comment]
please review

**Comment by szarnekow** [comment]
Should we change that into a Set implementation, that does Class.forName(..) internally on a contains(String)?

**Comment by cdietrich** [comment]
am not sure: usecase: with a jdk 8 generate for jdk 9 bree

**Comment by szarnekow** [comment]
Hmm true. Maybe a combination of both to be a little more robust against new types in the JDK?

**Comment by cdietrich** [comment]
i wonder anyway if there is a contstand list somewhere in javalang ...

**Comment by szarnekow** [comment]
Not that I'm aware of.

**Comment by kthoms** [comment]
LGTM

**Pull request merged**
