### PR TITLE
Fix for #525: Detect incomplete escape sequences

### PR DESCRIPTION
**Pull request by waqasilyas**
Signed-off-by: Waqas Ilyas <waqas.ilyas@gmail.com>

### CODE REVIEW

**Comment by cdietrich** [comment]
@waqasilyas are you still working on this pr or should we close it?

**Comment by waqasilyas** [comment]
@cdietrich No I am not working on this anymore. The fix and test updates are all in this pull request. It is up to you guys to take the next step.

**Comment by szarnekow** [comment]
I made minor adjustments to the logic. See here: https://github.com/eclipse/xtext-core/tree/waqasilyas-wi_issue525

**Comment by cdietrich** [comment]
replaced by https://github.com/eclipse/xtext-core/pull/847

**Pull request closed without merging**
