### PR TITLE
Solve Issue 1029

### PR DESCRIPTION
**Pull request by epoell**
[Issue 1029](https://github.com/eclipse/xtext-core/issues/1029)
Replaced ThreadLocal state.set(null) with state.remove(). And tried to decrement the calls of state.get() by keeping it in a variable if possible.
Might need a closer look, if this works. And sorry for the wrong number (1021 instead of 1029) in the commit! I got mixed up.

Signed-off-by: Eva Poell <epoell@itemis.com>

### CODE REVIEW

**Comment by cdietrich** [comment]
testing is currently blocked by jcenter having no current mwe metadata unfortunately

**Comment by epoell** [comment]
Is there something I can do about that, or may I just wait patiently?

**Comment by cdietrich** [comment]
no we have to be patient

**Comment by szarnekow** [comment]
I triggered a build

**Pull request merged**
