### PR TITLE
[eclipse/xtext#1976] pin explicit transitive deps in xtext.xtext.generator

### PR DESCRIPTION
**Pull request by cdietrich**
[eclipse/xtext#1976] pin explicit transitive deps in xtext.xtext.generator

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Review by LorenzoBettini — APPROVED** [review]
If I understand correctly, that's basically my original proposal apart from using api instead of compile (I don't know the difference in gradle). Besides that, I'm in favor of approval!

**Comment by cdietrich** [comment]
@LorenzoBettini  yes this is just a version of your patch for gradle 7

**Comment by LorenzoBettini** [comment]
@cdietrich OK, thanks for handling this.
I guess then we'll also have to change what the wizard generates in the POM, right?

**Comment by cdietrich** [comment]
@LorenzoBettini  what do you want to change?

**Comment by cdietrich** [comment]
yes unfortunately testing it is pain. so i would do it in 2nd pr

**Comment by cdietrich** [comment]
https://github.com/itemis/xtext-reference-projects/pull/227

**Review by szarnekow — APPROVED** [review]

**Pull request merged**
