### PR TITLE
Pin emf.ecore, ecore.xmi, and common dependencies

### PR DESCRIPTION
**Pull request by LorenzoBettini**
See https://github.com/eclipse/xtext/issues/2397

Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>

### CODE REVIEW

**Review by cdietrich — APPROVED** [review]

**Comment by LorenzoBettini** [comment]
@cdietrich Thanks for merging this!
I have started to do some experiments, but I'm not done yet. I think I still have to pin a few mwe2 dependencies.
I'll open a new PR when I'm ready.

**Comment by cdietrich** [comment]
@LorenzoBettini please note, the patch wont be visible before 2morrow

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini please note, the patch wont be visible before 2morrow

What did you mean by "the patch won't be visible before tomorrow"? Did you refer to the p2 site?

**Comment by cdietrich** [comment]
the p2 site and sonatype snapshots,
they are provided by https://ci.eclipse.org/xtext/job/releng/job/sign-and-deploy/ which runs nightly

**Comment by LorenzoBettini** [comment]
OK! Anyway, I tested directly by setting Maven repositories and plugin repositories of this shape (referring directly to the maven repository of the Jenkins job);

```xml
<repository>
	<id>custom-xtext-core</id>
	<name>Custom Xtext Core</name>
	<url>https://ci.eclipse.org/xtext/job/xtext-core/job/master/lastSuccessfulBuild/artifact/build/maven-repository/</url>
	<releases>
		<enabled>false</enabled>
	</releases>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```

Before the PR was merged, I used my branch in the URL.

That's the procedure you once taught me, if I remember correctly.

**Pull request merged**
