### PR TITLE
[eclipse/xtext#1282] Upgrade to EMF 2.15

### PR DESCRIPTION
**Pull request by kthoms**
Using latest EMF artifacts from Maven Central

### CODE REVIEW

**Comment by cdietrich** [comment]
I miss exclusions for bad transitive dependencies as we have it for jdt

**Comment by kthoms** [comment]
Where would you expect them?

**Comment by cdietrich** [comment]
There where the different emf plugins are used. See places for jdt. Let gradle plaint transitive dependencies. Make sure the plugins that should be used from platform are actually used

**Comment by cdietrich** [comment]
Alternatively do this after the bom update (am not sure we find time to actually test this in time, besides me all of the Xtext team did nothing to actually try and test it or find better solution)

**Comment by szarnekow** [comment]
This should be merged after the bom stuff.

**Comment by cdietrich** [comment]
obsolete

**Pull request closed without merging**
