### PR TITLE
Hs/validation fragment2 configurable issue

### PR DESCRIPTION
**Pull request by holgerschill**

### CODE REVIEW

**Comment by cdietrich** [comment]
miss a change for org.eclipse.xtext.xtext.ui.editor.validation.XtextValidatorConfigurationBlock

**Comment by holgerschill** [comment]
What do you mean with that?

**Comment by cdietrich** [comment]
inside eclipse the configureable issue code should be configurable through the preference page

**Comment by holgerschill** [comment]
Will do that.

**Comment by holgerschill** [comment]
Please have another look. Now the issues are configurable. Please look at PR in xtext-eclipse as well.

**Pull request merged**
