### PR TITLE
[431435] Bind generated EPackage and EFactory

### PR DESCRIPTION
**Pull request by kthoms**
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=431435

**Comment by kthoms** [comment]
Replaces https://github.com/eclipse/xtext/pull/976

Since the feature is off by default, no generated runtime module has to be changed. To test the feature, start a runtime eclipse, create a new project and add

```
			emfGenerator = {
				bindEPackageAndEFactory = true
			}
```

This will create bindings
```
	// contributed by org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2
	public MyDslPackage bindMyDslPackageToInstance() {
		return MyDslPackage.eINSTANCE;
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2
	public MyDslFactory bindMyDslFactoryToInstance() {
		return MyDslFactory.eINSTANCE;
	}
```

**Comment by meysholdt** [comment]
please revert. The review was not finished.

**Comment by meysholdt** [comment]
Ok, let's keep it merged since it was approved in the old pull request. I'm still not convinced since:
 - it increases the chance of exchanged code snippets from the web to not work in your local language
- it introduces a third pointer to the `EPackage` besides `EPackage.Registry` and `MyEPackage.eINSTANCE` even though people already have trouble keeping those two in sync in their test setups.
- as @svenefftinge said, it bypasses the EMF way of accessing EPackages.
- it is *really easy* to introduce these changes in your MyLanugageRuntime Module, if you want to have them.
- this change is incomplete, as imported EPackages are not registered.

**Comment by svenefftinge** [comment]
Also I don't really understand the use case. Why would you want to use injection for an EPackage?

**Comment by kthoms** [comment]
Just for convenience.

**Pull request merged**
