### PR TITLE
[LS] Fixed defect in signature help service.

### PR DESCRIPTION
**Pull request by kittaakos**
- It occurred when no arguments were used on use-side but were required
according to definition-side. Such cases parameter hints were not
available.
- Adjusted service interface name to Xtext conventions.

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
Associated task: #165

**Comment by svenefftinge** [comment]
Could you rebase?

**Comment by kittaakos** [comment]
Hmm, strange. Sure, I'll do it.

**Comment by kittaakos** [comment]
Did the merge. Does it work? I had some problems with security recently here. Please check the effective changes. Thanks!

**Comment by kittaakos** [comment]
Closing issue. It has been fixed meanwhile via e0705b0c41952c201f37b78ace378cfdfb467009 .

**Comment by kittaakos** [comment]
Reopening, I wanted to close something else. Sorry. Once I have reopened, I will fix the conflicts.

**Pull request merged**
