### PR TITLE
Hn issue1382

### PR DESCRIPTION
**Pull request by hannesN**
I added the suggested line into the IdeProjectDescriptor and updated the two tests using the wizards.

The gradle and maven build are working.

### CODE REVIEW

**Comment by cdietrich** [comment]
@miklossy i have the change in the xtend file? which java change do you refer to?

**Comment by cdietrich** [comment]
thx for the fix @hannesN

**Comment by cdietrich** [comment]
@kthoms would still be nice if you would find a few mins to have a look

**Comment by kthoms** [comment]
+1 The change looks reasonable. Don't have a LS that I could test with yet.

**Pull request merged**
