### PR TITLE
[329125] Avoid unnecessary parentheses in generated Antlr grammars

### PR DESCRIPTION
**Pull request by stadlerb**
https://bugs.eclipse.org/bugs/show_bug.cgi?id=329125

This changes the Antlr Grammar Generator to avoid duplicate parentheses as ANTLR3's parser generator seems to have trouble generating correct parsers with backtracking when duplicate parentheses meet alternatives.

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=329125

**Comment by spoenemann** [comment]
This is a quite big change. Could someone with some Antlr experience please review it?

**Comment by JanKoehnlein** [comment]
The Antlr grammar generator fragments are used by *all* of our users, and a change could potentially break quite a few of them. 

We should at least re-generate all test grammars and check for the impact from this change. Given that the real problem only appears when ```backtracking``` is enabled, which is really a discouraged setting, I'd rather not risk changing the Antlr generator. 

If we're sure it works, we should always enable it. If we're unsure, we could also consider shipping separate fragments for the backtracking users instead of adding a boolean parameter everywhere.

Opinions?

**Comment by cdietrich** [comment]
i'd prefer a separate fragment. backtracking is discouraged anyway since it leads to unexpected behaviour all over the place e.g. in content assist

**Comment by spoenemann** [comment]
@JanKoehnlein, @cdietrich: sounds sensible. Extracting the backtracking part to a new fragment would require some more work. Should we close this PR and describe what is to be done in a new issue?

**Comment by JanKoehnlein** [comment]
See eclipse/xtext#2589.

**Pull request closed without merging**
