### PR TITLE
handle null argument for projectConfig

### PR DESCRIPTION
**Pull request by kthoms**
refactored method to return null when precondition is not satisfied to remove one indentation layer
removed null guard for projectConfig later in the method

### CODE REVIEW

**Comment by cdietrich** [comment]
are all the other methods null safe regarding project config?

**Comment by kthoms** [comment]
All methods calling getTraceToTarget are safe to handle null as return value. asFile is safe, since it is not called with the result of getProjectConfig(sourceFile).

**Comment by cdietrich** [comment]
i still have the feeling we fix downstream errors that are caused somewhat upstream.
thus id be interested how the user gets into this situation

**Comment by kthoms** [comment]
The effect is just that no trace will be available for some situation we cannot reproduce. I don't know much enough about the tracing stuff.

**Comment by cdietrich** [comment]
me neither. thus i am unsure if we should go this way

**Comment by svenefftinge** [comment]
I agree with @cdietrich, that we should rather handle null pointers on the call site than making the parameters nullable.

**Comment by kthoms** [comment]
OK, will raise another PR to also assure that the method is not called with null parameter.

**Pull request merged**
