### PR TITLE
GH-712 adapt to breaking changes in lsp4j

### PR DESCRIPTION
**Pull request by JanKoehnlein**

### CODE REVIEW

**Comment by kthoms** [comment]
There is currently a dependency on 0.4.0-SNAPSHOT. What is the release date of lsp4j 0.4.0 Final? It must be before Xtext release date.

**Comment by cdietrich** [comment]
it will be this week

**Comment by JanKoehnlein** [comment]
Is it OK to merge? Failing tests are unrelated.

**Comment by kthoms** [comment]
OK to merge

**Pull request merged**
