### PR TITLE
[https://github.com/eclipse/xtext/issues/1486]

### PR DESCRIPTION
**Pull request by miklossy**
- Use xtext32.png instead of modeling32.png for the feature image.

Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
hi, where is the fix for umbrella?

**Comment by miklossy** [comment]
Do you mean that this [feature.xml](https://github.com/eclipse/xtext-umbrella/blob/5ee83150aac3ed65dc95ea567150efdac8033944/releng/org.eclipse.xtext.sdk.feature/feature.xml#L8) has to be changed too?

**Comment by cdietrich** [comment]
Yes

**Comment by miklossy** [comment]
Oh, thanks for the hint. I created the corresponding PR in the umbrella repository:
https://github.com/eclipse/xtext-umbrella/pull/162

**Pull request merged**
