### PR TITLE
GH-882: Fixed the inconsistency between the `range` and `selectionRange`.

### PR DESCRIPTION
**Pull request by kittaakos**
Added a test assertion to ensure `selectionRange` is always contained by the `range`.

Closes: #882.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

**Comment by kittaakos** [comment]
Please restart the build, it failed with HTTP 502:
```
1: Task failed with an exception.
-----------
* What went wrong:
Could not resolve all files for configuration ':xtendCompiler'.
> Could not resolve org.eclipse.platform:org.eclipse.core.resources:[3.12.0,4.0.0).
  Required by:
      project : > org.eclipse.xtend:org.eclipse.xtend.core:2.14.0 > org.eclipse.jdt:org.eclipse.jdt.core:3.13.102
   > Failed to list versions for org.eclipse.platform:org.eclipse.core.resources.
      > Unable to load Maven meta-data from https://ci.eclipse.org/xtext/job/xtend-bootstrap/lastStableBuild/artifact/build-result/maven-repository/org/eclipse/platform/org.eclipse.core.resources/maven-metadata.xml.
         > Could not get resource 'https://ci.eclipse.org/xtext/job/xtend-bootstrap/lastStableBuild/artifact/build-result/maven-repository/org/eclipse/platform/org.eclipse.core.resources/maven-metadata.xml'.
            > Could not GET 'https://ci.eclipse.org/xtext/job/xtend-bootstrap/lastStableBuild/artifact/build-result/maven-repository/org/eclipse/platform/org.eclipse.core.resources/maven-metadata.xml'. Received status code 502 from server: Proxy Error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Could not resolve all files for configuration ':org.eclipse.xtext.xtext.bootstrap:mwe2CompileClasspath'.
> Could not resolve org.eclipse.emf:org.eclipse.emf.common:[2.10.1,3).
  Required by:
      project :org.eclipse.xtext.xtext.bootstrap > org.eclipse.xtext:org.eclipse.xtext:2.14.0
      project :org.eclipse.xtext.xtext.bootstrap > org.eclipse.xtext:org.eclipse.xtext:2.14.0 > org.eclipse.xtext:org.eclipse.xtext.util:2.14.0
   > Failed to list versions for org.eclipse.emf:org.eclipse.emf.common.
      > Unable to load Maven meta-data from https://ci.eclipse.org/xtext/job/xtext-lib/job/master/lastStableBuild/artifact/build/maven-repository/org/eclipse/emf/org.eclipse.emf.common/maven-metadata.xml.
         > Could not get resource 'https://ci.eclipse.org/xtext/job/xtext-lib/job/master/lastStableBuild/artifact/build/maven-repository/org/eclipse/emf/org.eclipse.emf.common/maven-metadata.xml'.
            > Could not GET 'https://ci.eclipse.org/xtext/job/xtext-lib/job/master/lastStableBuild/artifact/build/maven-repository/org/eclipse/emf/org.eclipse.emf.common/maven-metadata.xml'. Received status code 502 from server: Proxy Error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
```

**Comment by cdietrich** [comment]
eclipse ci seems to be down cc @kthoms 
pushed your stuff here: http://services.typefox.io/open-source/jenkins/job/xtext-core/job/GH-882/

**Comment by kthoms** [comment]
Opened [539587](https://bugs.eclipse.org/bugs/show_bug.cgi?id=539587)

**Comment by kittaakos** [comment]
The CI is back. Thanks for taking care of it.

**Comment by kittaakos** [comment]
@cdietrich, is there anything holding back this PR? I could use the provided fix in other projects. Thanks!

**Comment by cdietrich** [comment]
I m still in holiday. @kthoms @svenefftinge please take care

**Pull request merged**
