### PR TITLE
run test with UTF-8 always #280

### PR DESCRIPTION
**Pull request by cdietrich**
run test with UTF-8 always #280

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by spoenemann** [comment]
I'd prefer to fix the single failing test instead of manipulating a system property. Why does the test depend on that property?

**Comment by cdietrich** [comment]
you can see the test fail when starting the test with
`-Dfile.encoding=ANSI_X3.4-1968`
which is the default encoding on the workstations i try to build xtext on

**Comment by spoenemann** [comment]
`AbstractXtextTests.doGetResource(InputStream, URI)` might also be a problem. The default implementation of `IEncodingProvider.Runtime` uses `Charset.defaultCharset()`, so the test might have to set a different default encoding there.

**Comment by cdietrich** [comment]
ill have a look

**Comment by cdietrich** [comment]
save is affected as well

**Comment by spoenemann** [comment]
Another thought: if it's too hard to fix the tests directly, we could add something like this to `java-compiler-settings.gradle`:
```
tasks.withType(Test) {
	systemProperty 'file.encoding', 'ISO-8859-1'
}
```
But a more direct fix is certainly favorable.

**Comment by cdietrich** [comment]
fixed problems locally

**Comment by cdietrich** [comment]
@spoenemann is it ok to merge now?

**Pull request merged**
